### ISSUE TITLE
Does not support "last Wednesday of the month" syntax

### ISSUE THREAD

**Issue by schmod** [grumBit/aws_cron_expression_validator#12]
**Describe the bug**
While it's not mentioned in AWS's documentation, the day-of-week portion of the cron expression can combine a number with the `L` wildcard to allow jobs to be scheduled on the last instance of a particular weekday of a month.  

[Quartz's documentation](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html) explains:
> L (“last”) - has different meaning in each of the two fields in which it is allowed. For example, the value “L” in the day-of-month field means “the last day of the month” - day 31 for January, day 28 for February on non-leap years. If used in the day-of-week field by itself, it simply means “7” or “SAT”. But if used in the day-of-week field after another value, it means “the last xxx day of the month” - for example “6L” means “the last friday of the month”. You can also specify an offset from the last day of the month, such as “L-3” which would mean the third-to-last day of the calendar month. When using the ‘L’ option, it is important not to specify lists, or ranges of values, as you’ll get confusing/unexpected results.

**To Reproduce**
Test the cron expression `0 2 ? * 5L *` 

**Expected behaviour**
This expression works in AWS, and should be considered to be valid by this library.  Instead, the error `Invalid day-of-week value '5L'` is produced.

**Comment by grumBit** [comment]
Re-opening as this wasn't completely fixed by PR #15, which doesn't handle suffixes to `L`. E.g. `L-2`.

**Comment by grumBit** [comment]
Hi @schmod , apologies for the very slow response to your issue. Thank you for reporting the problem and linking to Quartz's documentation. I wasn't aware AWS was using it. After going through the documentation, I noticed some other bugs. Hopefully the latest release addresses those problems and the one you spotted.
