### ISSUE TITLE
[BUG] Cron expressions can have 7 values, they aren't limited to 6.

### ISSUE THREAD

**Issue by icp277** [grumBit/aws_cron_expression_validator#13]
**Describe the bug**
If you provide more than 6 values in a cron expression, this error is raised: https://github.com/grumBit/aws_cron_expression_validator/blob/master/src/aws_cron_expression_validator/validator.py#L64

**To Reproduce**
Steps to reproduce the behaviour.
Place 7 expression in a cron schedule, example: 0 1-7/2,11-23/2 * * ? *
**Expected behaviour**
For it to work. 
**Screenshots**

**Additional context**

**Comment by benfrodo** [comment]
Hi @icp277, I don't think the issue here is length - the expression is split by space, and the example you give is still 6 elements long by that metric - but rather that this combination of lists and slash expressions isn't supported.

I'm happy to take a look into this :)

**Comment by icp277** [comment]
Ah, I see your point and I concur. I don't know if the use case of that many slashes is going to be a common occurrence and doesn't seem worth the time for a single user. I appreciate your response.

**Comment by grumBit** [comment]
Hi @icp277, thank you for reporting the problem and sorry for the slow reply to it. Hopefully the latest release fixes it and some other bugs I spotted.
